backend:
    name: github
    repo: sidag95/netlify-cms-custom-block-element-test
    squash_merges: true
publish_mode: editorial_workflow
media_folder: "assets/images"
public_folder: "/assets/images"
collections:
  - name: "routes" # Used in routes, e.g., /admin/collections/src
    label: "Routes" # Used in the UI
    folder: "src/routes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    nested: { depth: 100 }
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "select", options: ["api", "product"]}
      - {label: "Title here", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Nav Tree", name: "tree", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: "posts" # Used in routes, e.g., /admin/collections/src
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    nested: { depth: 100 }
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "select", options: ["api", "product"]}
      - {label: "Title here", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Nav Tree", name: "tree", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
  
  - name: "partials" # Used in routes, e.g., /admin/collections/blog
    label: "Partials" # Used in the UI
    folder: "src/partials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  