backend:
    name: github
    repo: sidag95/netlify-cms-custom-block-element-test
    squash_merges: true
publish_mode: editorial_workflow
media_folder: "/assets/images"
public_folder: "/assets/images"
site_url: "https://razorpay.com/docs"
collections:
  - name: "routes" # Used in routes, e.g., /admin/collections/src
    label: "Routes" # Used in the UI
    folder: "src/routes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    nested: { depth: 100 }
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{media_folder}}"
    summary: "Title: {{title}} | written by: {{commit_author | upper}} | last updated at: {{commit_date | date('YYYY-MM-DD')}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "select", options: ["api", "product"]}
      - {label: "Title here", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string", required: false}
      - {label: "Nav Tree", name: "tree", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
  
  - name: "partials" # Used in routes, e.g., /admin/collections/blog
    label: "Partials" # Used in the UI
    folder: "src/partials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "redirects" # Used in routes, e.g., /admin/collections/blog
    label: "Redirects" # Used in the UI
    files: 
      - label: "Redirects"
        name: "redirects-common"
        file: "src/redirects-common.yml"
        fields: # The fields for each document, usually in front matter
          - {label: "Body", name: "body", widget: "markdown"}
            
      - label: "Axis Redirects"
        name: "redirects-axis"
        file: "src/redirects-axis.yml"
        fields: # The fields for each document, usually in front matter
          - {label: "Body", name: "body", widget: "markdown"}
  