name: Dummy workflow

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: commit-status-updater
        uses: ouzi-dev/commit-status-updater@v1.1.2
        env:
          DEPLOY_URL: http://betasite.razorpay.com/docs/razorpay/${{steps.extract_branch.outputs.branch}}
        with:
          status: "success"
          name: "deploy"
          url: ${{ env.DEPLOY_URL }}
