name: Dummy workflow

on: pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo
        run: echo hi
      - name: Update status to pending
        uses: geekodour/gh-actions-custom-status@v0.0.4
        env:
          BRANCH: ${{github.ref#refs/heads/}}
        with:
          args: >-
            --state=success
            --context=deploy-preview
            --target_url=https://betasite.razorpay.com/docs/razorpay/${BRANCH}